version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "8888"
  nginx:
    image: nginx:latest
    volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./key.pem:/root/ssl/key.pem
      - ./cert.pem:/root/ssl/cert.pem
    depends_on:
      - app
    ports:
      - "443:443"
